language: r
warnings_are_errors: true
sudo: required
cache: packages

matrix:
    include:
        - r: oldrel
          os: linux
          dist: trusty # 14.04
        - r: release
          os: linux
          dist: trusty
          env: R_CODECOV=true
        - r: devel
          os: linux
          dist: trusty
        - r: oldrel
          os: osx
        - r: release
          os: osx
          #- r: devel
          #os: osx

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
